services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
    #$projectDir: '%kernel.project_dir%'

  Markocupic\NavPageContainer\:
    resource: ../../
    exclude: ../../{DependencyInjection,Resources,Model}


