services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
        #$projectDir: '%kernel.project_dir%'

    Markocupic\NavPageContainer\:
        resource: ../src/
        exclude: ../../{DependencyInjection,Resources,Model}


